### ISSUE TITLE
Issue calling the get_documents() method from llama-index/core/readers

### ISSUE THREAD

**Issue by LNshuti** [logan-markewich/agent-as-a-service#1]
Hi Logan, I am experimenting running your repo with Docker, and getting an Import error. Do you see a similar error when you run the container on your machine? Below is my traceback: 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/app/app/engine/generate.py", line 18, in generate_datasource
    documents = get_documents()
                ^^^^^^^^^^^^^^^
  File "/app/app/engine/loaders/__init__.py", line 26, in get_documents
    documents = get_file_documents(FileLoaderConfig(**loader_config))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/engine/loaders/file.py", line 39, in get_file_documents
    return reader.load_data()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/readers/file/base.py", line 565, in load_data
    SimpleDirectoryReader.load_file(
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/readers/file/base.py", line 394, in load_file
    default_file_reader_cls = SimpleDirectoryReader.supported_suffix_fn()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/readers/file/base.py", line 39, in _try_loading_included_file_formats    raise ImportError("`llama-index-readers-file` package not found")
ImportError: `llama-index-readers-file` package not found
```

**Comment by logan-markewich** [comment]
Ah I might have missed a dependency in the toml, I'll double check

**Comment by logan-markewich** [comment]
Fixed and pushed!
